[package]
name = "Polynomial_Search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
num-bigint = "0.3"
num-traits = "=0.2.11"
rand = "0.8"
libc = "0.2.48"